/*
 * This source file was generated by the Gradle 'init' task
 */
package cs2.hello;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void printNumbers(int... nums) {
        for (int num : nums) {
            System.out.println(num);
        }
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        printNumbers(1, 2, 3, 4, 5);
    }
}
